/**
 * BookStore API
 * BookStore API documentation
 *
 * OpenAPI spec version: 1.0.0
 * Contact: fj.dearcos@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Book { 
    /**
     * Book identifier
     */
    id?: number;
    /**
     * Title of the book
     */
    title: string;
    /**
     * Description fo the book
     */
    description?: string;
    /**
     * Price of the book
     */
    unitCost?: number;
    /**
     * ISBN of the book
     */
    isbn: string;
    /**
     * Date when book was published
     */
    publicationDate?: Date;
    /**
     * Number of pages of the book
     */
    numberOfPages?: number;
    /**
     * URL with the book cover image
     */
    imageUrl?: string;
    /**
     * Language of the book
     */
    language?: Book.LanguageEnum;
}
export namespace Book {
    export type LanguageEnum = 'ENGLISH' | 'FRENCH' | 'SPANISH' | 'PORTUGUESE' | 'ITALIAN' | 'FINISH' | 'GERMAN' | 'DUTCH' | 'RUSSIAN';
    export const LanguageEnum = {
        ENGLISH: 'ENGLISH' as LanguageEnum,
        FRENCH: 'FRENCH' as LanguageEnum,
        SPANISH: 'SPANISH' as LanguageEnum,
        PORTUGUESE: 'PORTUGUESE' as LanguageEnum,
        ITALIAN: 'ITALIAN' as LanguageEnum,
        FINISH: 'FINISH' as LanguageEnum,
        GERMAN: 'GERMAN' as LanguageEnum,
        DUTCH: 'DUTCH' as LanguageEnum,
        RUSSIAN: 'RUSSIAN' as LanguageEnum
    };
}